Update Step1-styles and add tooltip
jivko25/Self-Guided-Tour-FE pull request #59
Opened 2024-07-04 06:34 UTC by AntonMurtin

2024-07-04 07:44 UTC, jivko25 commented
1. Ще можем ли да сменим цвета на tooltip-а да е същото жълто, което използваме в сайта и да изглежда по този начин: 
![image](https://github.com/jivko25/Self-Guided-Tour-FE/assets/59103450/a1da8d54-781d-4960-89c2-7396d1ea8b5d)
2. Ще можеш ли да оправиш конфликтите?

Не е нужно да правиш нов бранч, нов PR и т.н, просто пушни промените в този си бранч и PR-а автоматично ще се ъпдейтне

2024-07-04 07:46 UTC, jivko25 requested changes
Трябва да се смени цвета на tooltip-а да бъде жълт

2024-07-04 07:54 UTC, AntonMurtin commented
Смених цвета и направих commit, но за конфликтите не ми е ясно, ако можеш да ми съдействаш

2024-07-07 20:44 UTC, merged

2024-07-07 20:45 UTC, jivko25 commented
Моля прави PR-ите към dev бранча, а не към main, след като направих PR-а към dev, конфликта изчезна